name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: touch config-prod.env config-dev.env

    - name: Build the Docker image
      run: |
        docker network prune -f
        docker-compose build komidabot-dev komidabot-db

    - name: Start supporting services
      run: docker-compose up -d komidabot-db

    - name: Wait for database ready
      run: docker-compose run --rm --entrypoint=./wait-postgres.sh komidabot-dev
      timeout-minutes: 1

    - name: Run the tests
      run: docker-compose run --rm --entrypoint=python komidabot-dev manage.py test

    - name: Cleanup
      run: docker-compose stop
